apps/code_release/urls.py
# _*_ coding: utf-8 _*_
from django.conf.urls import url
from .views import *

urlpatterns = [
    url('^apply/$', ApplyView.as_view(), name='apply'),
    url('^apply_list/$', ApplyListView.as_view(), name='apply_list'),
    url('^deploy/(?P<pk>[0-9]+)?/$',  DeployView.as_view(), name='deploy'),
    url('^deploy_history/$', DeployHistoryView.as_view(), name='deploy_history'),

    # 获取某个项目的所有标签(版本)
    url('^get_project_versions/$', GetProjectVersionsView.as_view(), name='get_project_versions'),
]

opsweb/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from dashboard.views import LoginView, LogoutView, IndexView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^$', IndexView.as_view(), name='index'),
    url('^index/', IndexView.as_view(), name='index'),
    url('^login/', LoginView.as_view(), name='login'),
    url('^logout/', LogoutView.as_view(), name='logout'),
    url('^dashboard/', include("dashboard.urls", namespace="dashboard")),
    url('^work_order/', include('work_order.urls', namespace='work_order')),
    url('^cmdb/', include('cmdb.urls', namespace='cmdb')),
    url('^task/', include('tasks.urls', namespace='task')),
    url('^books/', include('books.urls', namespace='books')),
    url('^projects/', include('projects.urls', namespace='projects')),
    url('^deploy/', include('code_release.urls', namespace='deploy')),
]

apps/cmdb/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from dashboard.models import UserProfile


class Product(models.Model):
    name = models.CharField("业务线名称", max_length=32)
    pid = models.ForeignKey("self", null=True, blank=True, verbose_name="上级业务线")
    module_letter = models.CharField("字母简称", max_length=32)
    op_interface = models.ManyToManyField(UserProfile, verbose_name='运维负责人', related_name='op')
    dev_interface = models.ManyToManyField(UserProfile, verbose_name='业务负责人', related_name='dev')

    def __str__(self):
        return "{}".format(self.module_letter)


class Host(models.Model):
    STATUS = (
        ('Running', '运行中'),
        ('Starting', '启动中'),
        ('Stopping', '停止中'),
        ('Stopped', '已停止')
    )
    CHARGE_TYPE = (
        ('PrePaid', '预付费'),
        ('PostPaid', '后付费')
    )
    CLOUD = (
        ('aliyun', '阿里云'),
        ('qcloud', '腾讯云')
    )

    cloud_type = models.CharField(max_length=20, choices=CLOUD, default='aliyun', verbose_name='云主机类型')
    instance_id = models.CharField(max_length=22, unique=True, verbose_name='实例ID')
    instance_name = models.CharField(max_length=22, verbose_name='实例的显示名称')
    description = models.CharField(max_length=128, null=True, blank=True, verbose_name='实例的描述')
    image_id = models.CharField(max_length=50, verbose_name='镜像ID')
    region_id = models.CharField(max_length=30, verbose_name='实例所属地域ID')
    zone_id = models.CharField(max_length=30, verbose_name='实例所属可用区')
    cpu = models.IntegerField(verbose_name='CPU核数')
    memory = models.IntegerField(verbose_name='内存大小，单位: GB')
    instance_type = models.CharField(max_length=30, verbose_name='实例资源规格')
    status = models.CharField(max_length=8, choices=STATUS, default='Running', verbose_name='实例状态')
    hostname = models.CharField(max_length=23, blank=True, null=True, verbose_name='实例机器名称')
    public_ip = models.GenericIPAddressField(blank=True, null=True, verbose_name='公网IP')
    private_ip = models.GenericIPAddressField(verbose_name='私网IP')
    os_type = models.CharField(max_length=10, default='linux', verbose_name='操作系统类型')
    os_name = models.CharField(max_length=20, default='', verbose_name='操作系统名称')
    instance_charge_type = models.CharField(max_length=8, default='PrePaid', choices=CHARGE_TYPE, verbose_name='实例的付费方式')
    creation_time = models.DateTimeField(verbose_name='创建时间')
    expired_time = models.DateTimeField(verbose_name='过期时间')
    business_line = models.ManyToManyField('Product', blank=True, verbose_name='业务线')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='入库时间')
    update_time = models.DateTimeField(auto_now=True, verbose_name='更新时间')

    class Meta:
        verbose_name = '主机'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.instance_name


class Disk(models.Model):
    """
        磁盘信息
    """
    DEVICE_TYPE = (
        ('system', '系统盘'),
        ('data', '数据盘')
    )

    host = models.ForeignKey('Host', verbose_name='主机')
    disk_id = models.CharField(max_length=22, null=True, blank=True, verbose_name='磁盘ID')
    device = models.CharField(max_length=15, null=True, blank=True, verbose_name='所属Instance的Device信息')
    size = models.IntegerField(verbose_name='磁盘大小，单位GB')
    type = models.CharField(default='data', max_length=6, choices=DEVICE_TYPE, verbose_name='磁盘类型')
    creation_time = models.DateTimeField(verbose_name='创建时间')
    expired_time = models.DateTimeField(verbose_name='过期时间')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='入库时间')
    update_time = models.DateTimeField(auto_now=True, verbose_name='更新时间')

    class Meta:
        verbose_name = '磁盘'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.device

templates/deploy/apply.html
{% extends "base.html" %}

{% block title %}申请发布{% endblock %}


{% block breadcrunb %}
  <h1>
     Dashboard
    <small>Version 2.0</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">申请发布</li>
  </ol>
{% endblock %}



{% block content %}


<!-- Main row -->
<div class="row">
<!-- Left col -->
<div class="col-md-12">

<!-- TABLE: LATEST ORDERS -->
<div class="box box-info">

<div class="box-header with-border">
  <h3 class="box-title">申请发布</h3>
  <div class="box-tools pull-right">
    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
    </button>
    <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
  </div>
</div>
<!-- /.box-header -->

<div class="box-body">
    <form method="post" action="" class="form-horizontal">
        {% if msg %}
            <div class="alert alert-success alert-dismissable">
                <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                {{ msg | safe }}
            </div>
        {% elif errmsg %}
            <div class="alert alert-danger alert-dismissable">
                <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                {{ errmsg | safe }}
            </div>
        {% endif %}


        <div class="form-group"><label class="col-sm-2 control-label">选择项目：</label>
            <div class="col-sm-8">
                <select name="name" id="name" class="select2_demo_3 form-control">
                    <option selected="selected">----请选择----</option>
                    {% for user_project in user_projects %}
                        <option value="{{ user_project.id }}/{{ user_project.name }}">{{ user_project.namespace.name }} / {{ user_project.name }}</option>
                    {% endfor %}
                </select>
                 {% for error in forms.name.errors %}<span style="color: red">{{ error }}</span>{% endfor %}
            </div>
        </div>
        <div class="hr-line-dashed"></div>

        <div class="form-group"><label class="col-sm-2 control-label">选择版本：</label>
            <div class="col-sm-8">
                <!-- select name="project_version" id = "project_version"  class="select_version form-control" onchange="getTagDesc(this.id)" -->
                <select name="project_version" id = "project_version"  class="select_version form-control">
                   <option selected="selected">----请选择----</option>
                </select>
                 {% for error in forms.project_version.errors %}<span style="color: red">{{ error }}</span>{% endfor %}
            </div>
        </div>
        <div class="hr-line-dashed"></div>

        <div class="form-group"><label class="col-sm-2 control-label">版本描述：</label>
            <div class="col-sm-8">
                <input type="text" name ="version_desc" id="version_desc" class="form-control" readonly="readonly"  value="" placeholder="版本描述" />
            </div>
        </div>
        <div class="hr-line-dashed"></div>

        <div class="form-group"><label class="col-sm-2 control-label">指派给：</label>
            <div class="col-sm-8">
                <select name="assigned_to" class="select2_demo_4 form-control">
                   <option selected="selected">----请选择----</option>
                    {% for user in assign_to_users %}
                        <option value="{{ user.id }}">{{ user.name_cn }}</option>
                    {% endfor %}
                </select>
                {% for error in forms.assigned_to.errors %}<span style="color: red">{{ error }}</span>{% endfor %}
            </div>
        </div>
        <div class="hr-line-dashed"></div>

         <div class="form-group"><label class="col-sm-2 control-label">更新详情：</label>
            <div class="col-sm-8">
             <textarea class="form-control" name ="update_detail" rows="5" placeholder="更新详情"></textarea>
             {% for error in forms.update_detail.errors %}<span style="color: red">{{ error }}</span>{% endfor %}
            </div>
        </div>
        <div class="hr-line-dashed"></div>

        <div class="form-group">
            <div class="col-sm-4 col-sm-offset-2">
                <button id="submit_button" class="btn btn-primary" type="submit">申请</button>
                <button class="btn btn-white" type="reset">取消</button>
            </div>
        </div>
    </form>

</div>

</div>
</div>
</div>




{% endblock %}

{% block js %}
        $(".select2_demo_3").select2({
            placeholder: "请选择你要申请上线的项目",
            allowClear: true
        });

        $(".select_version").select2({
           placeholder: "请您选择要发布的版本",
            allowClear: true
        });

        $(".select2_demo_4").select2({
                placeholder: "指派给你要申请的人",
                allowClear: true
        });

        var tags = '';
        $("#name").change(function(){
            var project_id = $(this).val()
            $.ajax({
                type: "GET",
                url: "{% url 'deploy:get_project_versions' %}",
                data:{"project_id": project_id},
                success: function(data){
                    console.log(data);
                    var option_html = "<option selected>----请选择----</option>";
                    tags = data
                    $.each(data, function(i,k) {
                        option_html += "<option value="+ k[0]+">"+ k[0] + "</option>"
                    });
                    $("#project_version").html(option_html);

                 }
            })
        })

       $("#project_version").change(function(){
            var tag = $(this).val()
            $.each(tags, function(i,k) {
                 if(tag == k[0]){
                    console.log(k[1])
                   $('#version_desc').val(k[1]);
                 }
            })
         })


{% endblock %}

templates/deploy/apply_list.html
{% extends "base.html" %}

{% block title %}首页{% endblock %}


{% block breadcrunb %}
  <h1>
     Dashboard
    <small>Version 2.0</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">申请列表</li>
  </ol>
{% endblock %}



{% block content %}

<!-- Main row -->
<div class="row">
<!-- Left col -->
<div class="col-md-12">

<!-- TABLE: LATEST ORDERS -->
<div class="box box-info">


    <div class="box-header with-border">
      <h3 class="box-title">发布申请列表</h3>
      <div class="box-tools pull-right">
        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
        </button>
        <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
      </div>
    </div>
    <!-- /.box-header -->

    <div class="box-body">

     <div style="margin-bottom: 10px;height: 30px" class="row">
        <form style="float: right;width: 20%;margin-right: 1%">
        <div  class="input-group">
            <input type="text" class="form-control" name="keyword"
                 placeholder="标题|内容|结果" value="{% if keyword %} {{ keyword }} {% endif %}">
            <div class="input-group-btn">
               <button id='search_btn' type="submit" class="btn btn-sm btn-primary">搜索</button>
            </div>
        </div>
        </form>
     </div>


    <div class="table-responsive">
    <table class="table table-bordered table-striped footable toggle-arrow-tiny" data-page-navigation=".paginations">
        <thead>
            <tr>
                <th class="text-center">项目名称</th>
                <th class="text-center">项目版本</th>
                <th class="text-center">版本描述</th>
                <th class="text-center">申请人</th>
                <th class="text-center">发布人</th>
                <th class="text-center">发布状态</th>
                <th class="text-center">申请时间</th>
                <th class="text-center">操作</th>
            </tr>
        </thead>
        <tbody>
         {% for project in apply_list %}
            <tr class="gradeX {{ project.id }}">
                <td class="text-center">{{ project.name }}</td>
                <td class="text-center"> {{ project.project_version }} </td>
                <td class="text-center"> {{ project.version_desc}} </td>
                <td class="text-center"> {{ project.applicant.name_cn}} </td>
                <td class="text-center"> {{ project.assigned_to.name_cn}} </td>
                <td class="text-center"><span class="label {% if project.status == 0 %}label-success{% elif project.status == 1 %}label-warning{% endif %}">{{ project.get_status_display}}</span></td>
                <td class="text-center">{{ project.apply_time}}</td>
                <td class="text-center">
                    {% if request.user.id == project.assigned_to_id %}
                        <a href="{% url 'deploy:deploy'  project.id  %}" class="btn btn-xs btn-info">{% if project.status == 0 %}灰度{% elif project.status == 1 %}上线{% endif %}</a>
                    {% else %}
                        <a href="{% url 'deploy:deploy'  project.id %}" class="btn btn-xs btn-info">详情</a>
                    {% endif %}
                    {% if request.user.id == project.applicant_id  or request.user.id == project.assigned_to_id%}
                        <button data-id="{{ project.id }}" class="btn btn-xs btn-danger apply-cancel">取消</button>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}

        </tbody>
    </table>

    </div><!-- /.table-responsive -->

    <div class="row">
      <div class="col-sm-6">
         <div class="dataTables_info" id="editable_info" role="status" aria-live="polite">
             显示 [{{ paginator.count }}] 条数据中的 第 [{{ page_obj.start_index}}] 至 [{{ page_obj.end_index }}] 的数据
         </div>
      </div>

      {% include 'paginator.html' %}
    </div><!-- /.paginator -->

</div>
<!-- /.box-body -->

</div>
  <!-- /.box -->
</div>
<!-- /.col -->
</div>
<!-- /.row -->


{% endblock %}

{% block js %}

$('.apply-cancel').click(function() {
        var apply_id = $(this).attr('data-id');
        swal({
            title: "你确定取消上线?",
            text: "取消上线后，需要重新申请",
            type: "warning",
            showCancelButton: true,
            cancelButtonText:"取消",
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "确定",
            closeOnConfirm: false
        }, function () {
            $.ajax({
                type: "POST",
                url: "{% url 'deploy:apply_list' %}",
                data:{"apply_id": apply_id},
                success: function(data){
                    console.log(data);
                            swal({
                                title: "是",
                                text:"取消成功",
                                type: "success",
                                confirmButtonText: "确定"
                            }, function () {
                                $("."+ apply_id).remove();
                            });
             }
            });
        });
})


{% endblock %}

templates/deploy/deploy.html
{% extends "base.html" %}

{% block title %}发布系统{% endblock %}


{% block breadcrunb %}
  <h1>
     Dashboard
    <small>Version 2.0</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">发布进度</li>
  </ol>
{% endblock %}



{% block content %}


<!-- Main row -->
<div class="row">
<!-- Left col -->
<div class="col-md-12">

<!-- TABLE: LATEST ORDERS -->
<div class="box box-info">

<div class="box-header with-border">
  <h3 class="box-title">发布进度</h3>
  <div class="box-tools pull-right">
    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
    </button>
    <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
  </div>
</div>
<!-- /.box-header -->

<div class="box-body">
    {% if msg %}
            <div class="alert alert-success alert-dismissable">
                <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                {{ msg | safe }}
            </div>
        {% elif errmsg %}
            <div class="alert alert-danger alert-dismissable">
                <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                {{ errmsg | safe }}
            </div>
    {% endif %}

     <div class="ibox-title">
        <ul class="nav nav-pills nav-justified step step-arrow">
            <li class="active">
                <a>申请中</a>
            </li>
            <li class="{% if deploy.status >= 1 %}active{% endif %}">
                <a>灰度</a>
            </li>
            <li class="{% if deploy.status >= 2%}active{% endif %}">
                <a>上线完成</a>
            </li>
        </ul>
    </div>
    <br>
    <br>


    <form method="post" action="" class="form-horizontal">

        <div class="form-group"><label class="col-sm-2 control-label">项目名称：</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" readonly="readonly" name="name" value="{{ deploy.name }}" placeholder="项目名称">
            </div>
        </div>

        <div class="hr-line-dashed"></div>
        <div class="form-group"><label class="col-sm-2 control-label">发布版本：</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" readonly="readonly" name ="project_version" value="{{ deploy.project_version }}" placeholder="发布版本" />

          </div>
        </div>

        <div class="hr-line-dashed"></div>
        <div class="form-group"><label class="col-sm-2 control-label">版本描述：</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" readonly="readonly" name ="version_desc" value="{{ deploy.version_desc }}" placeholder="版本描述" />
            </div>
        </div>

        <div class="hr-line-dashed"></div>
        <div class="form-group"><label class="col-sm-2 control-label">上线人：</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" readonly="readonly" name ="assigned_to" value="{{ deploy.assigned_to.name_cn }}" placeholder="版本描述" />
            </div>
        </div>

        <div class="hr-line-dashed"></div>
        <div class="form-group"><label class="col-sm-2 control-label">更新详情：</label>
            <div class="col-sm-8">
                <textarea class="form-control" readonly="readonly" name ="update_detail" rows="3" placeholder="更新详情">{{ deploy.update_detail }}</textarea>
            </div>
        </div>

        <div class="hr-line-dashed"></div>
        <div class="form-group">
            <div class="col-sm-4 col-sm-offset-2">
            {% if request.user.id == deploy.assigned_to_id %}
                {% if deploy.status == 0 %}
                    <button  class="btn btn-primary" type="submit">灰度</button>
                {% elif deploy.status == 1 %}
                    <button  class="btn btn-primary" type="submit">上线</button>
                {% elif deploy.status == 2 %}
                    <button class="btn btn-primary" type="submit">完成</button>
                {% endif %}
            {% elif request.user.id == deploy.applicant_id %}
                <button class="btn btn-primary" type="button">催一下</button>
            {% else %}

            {% endif %}
            </div>
        </div>

    </form>

</div>

</div>
</div>
</div>




{% endblock %}

{% block js %}


{% endblock %}

templates/deploy/deploy_history.html
{% extends "base.html" %}

{% block title %}首页{% endblock %}


{% block breadcrunb %}
  <h1>
     Dashboard
    <small>Version 2.0</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">发布历史</li>
  </ol>
{% endblock %}



{% block content %}

<!-- Main row -->
<div class="row">
<!-- Left col -->
<div class="col-md-12">

<!-- TABLE: LATEST ORDERS -->
<div class="box box-info">


    <div class="box-header with-border">
      <h3 class="box-title">发布历史</h3>
      <div class="box-tools pull-right">
        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
        </button>
        <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
      </div>
    </div>
    <!-- /.box-header -->

    <div class="box-body">

     <div style="margin-bottom: 10px;height: 30px" class="row">
        <form style="float: right;width: 20%;margin-right: 1%">
        <div  class="input-group">
            <input type="text" class="form-control" name="keyword"
                 placeholder="标题|内容|结果" value="{% if keyword %} {{ keyword }} {% endif %}">
            <div class="input-group-btn">
               <button id='search_btn' type="submit" class="btn btn-sm btn-primary">搜索</button>
            </div>
        </div>
        </form>
     </div>


    <div class="table-responsive">
    <table class="table table-bordered table-striped footable toggle-arrow-tiny" data-page-navigation=".paginations">
        <thead>
            <tr>
                <th class="text-center">项目名称</th>
                <th class="text-center">项目版本</th>
                <th class="text-center">版本描述</th>
                <th class="text-center">申请人</th>
                <th class="text-center">发布人</th>
                <th class="text-center">发布状态</th>
                <th class="text-center">申请时间</th>
            </tr>
        </thead>
        <tbody>
         {% for project in deploy_history %}
            <tr class="gradeX {{ project.id }}">
                <td class="text-center">{{ project.name }}</td>
                <td class="text-center"> {{ project.project_version }} </td>
                <td class="text-center"> {{ project.version_desc}} </td>
                <td class="text-center"> {{ project.applicant.name_cn}} </td>
                <td class="text-center"> {{ project.assigned_to.name_cn}} </td>
                <td class="text-center"><span class="label {% if project.status == 2 %}label-success{% elif project.status == 3 %}label-warning{% endif %}">{{ project.get_status_display}}</span></td>
                <td class="text-center">{{ project.apply_time}}</td>
            </tr>
        {% endfor %}

        </tbody>
    </table>

    </div><!-- /.table-responsive -->

    <div class="row">
      <div class="col-sm-6">
         <div class="dataTables_info" id="editable_info" role="status" aria-live="polite">
             显示 [{{ paginator.count }}] 条数据中的 第 [{{ page_obj.start_index}}] 至 [{{ page_obj.end_index }}] 的数据
         </div>
      </div>

      {% include 'paginator.html' %}
    </div><!-- /.paginator -->

</div>
<!-- /.box-body -->

</div>
  <!-- /.box -->
</div>
<!-- /.col -->
</div>
<!-- /.row -->


{% endblock %}
