apps/books/urls.py
# coding=utf-8

from django.conf.urls import include, url
from books import publish, author, book

urlpatterns = [
    url(r'^publishlist/$', publish.PublishListView.as_view(), name='publish_list'),
    url(r'^publishdetail/(?P<pk>\d+)?/?$', publish.PublishDetailView.as_view(), name='publish_detail'),

    url(r'^authorlist/$', author.AuthorListView.as_view(), name='author_list'),
    url(r'^authordetail/(?P<pk>\d+)?/?$', author.AuthorDetailView.as_view(), name='author_detail'),
    url(r'^booklist/$', book.BookListView.as_view(), name='book_list'),
    url(r'^bookdetail/(?P<pk>\d+)?/?$', book.BookDetailView.as_view(), name='book_detail'),
    url(r'^bookadd/$', book.BookAddView.as_view(), name='book_add'),
]

opsweb/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from dashboard.views import LoginView, LogoutView, IndexView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^$', IndexView.as_view(), name='index'),
    url('^index/', IndexView.as_view(), name='index'),
    url('^login/', LoginView.as_view(), name='login'),
    url('^logout/', LogoutView.as_view(), name='logout'),
    url('^dashboard/', include("dashboard.urls", namespace="dashboard")),
    url('^work_order/', include('work_order.urls', namespace='work_order')),
    url('^cmdb/', include('cmdb.urls', namespace='cmdb')),
    url('^task/', include('tasks.urls', namespace='task')),
    url('^books/', include('books.urls', namespace='books')),
    url('^projects/', include('projects.urls', namespace='projects')),
    url('^deploy/', include('code_release.urls', namespace='deploy')),
]

apps/books/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class Publish(models.Model):
    '''
    出版商
    '''
    name = models.CharField(max_length=30, verbose_name='出版商名称')
    address = models.CharField(max_length=5, verbose_name='出版商地址')
    city = models.CharField(max_length=60, verbose_name='出版商城市',  null=True, blank=True)

    class Meta:
        verbose_name = '出版商信息'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name

class Author(models.Model):
    '''
    作者
    '''
    name = models.CharField(max_length=40,verbose_name='作者名')
    email = models.EmailField(verbose_name='作者邮箱')
    phone = models.CharField(max_length=11, verbose_name='手机号码', null=True, blank=True)
    address = models.CharField(max_length=128, verbose_name='作者地址',null=True, blank=True)

    class Meta:
        verbose_name = '作者信息'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name

class Book(models.Model):
    '''
    图书
    '''
    name = models.CharField("书名", max_length=100)
    # 作者和书是多对多的关系
    authors = models.ManyToManyField(Author, verbose_name="作者")
    # 一本书只能被一家出版，出版商可以出版多本书
    publisher = models.ForeignKey(Publish, verbose_name="出版社")
    publication_date = models.DateField("出版时间")

    class Meta:
        verbose_name = '图书信息'
        verbose_name_plural = verbose_name
        ordering = ['-publication_date']

    def __unicode__(self):
        return self.name

apps/books/forms.py
# _*_ coding: utf-8 _*_

from django.forms import ModelForm
from dashboard.models import UserProfile
from books.models import Publish, Author, Book
from django.contrib.auth.models import Permission,Group
from dashboard.models import UserProfile

class PublishForm(ModelForm):
    class Meta:
        model = Publish
        fields = "__all__"
class AuthorForm(ModelForm):
    class Meta:
        model = Author
        fields = "__all__"

class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = "__all__"

class PowerForm(ModelForm):
    class Meta:
        model = Permission
        fields = "__all__"
class PowerUpdateForm(ModelForm):
    class Meta:
        model =Permission
        fields = ["name","codename"]

class UserForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ["username","name_cn","email","phone"]

class UserUpdataForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ["name_cn","phone","email"]

class GroupUpdateForm(ModelForm):
    class Meta:
        model = Group
        fields = ["name"]
class GroupForm(ModelForm):
    class Meta:
        model = Group
        fields = "__all__"

apps/books/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.db.models import Q
from django.http import JsonResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.shortcuts import render
from pure_pagination.mixins import PaginationMixin
from django.contrib.auth.mixins import LoginRequiredMixin

from django.conf import settings
from books.models import Publish, Author, Book
from books.forms import BookForm


# Create your views here.

templates/books/author_detail.html
{% extends "base.html" %}

  {% block title %}作者信息{% endblock %}
  {% block breadcrunb %}
      <h1>
         Dashboard
        <small>Version 2.0</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">作者信息</li>
      </ol>
  {% endblock %}


{% block content %}

<div class="row">
      <!-- Left col -->
        <div class="col-md-12">
        <div class="box box-info">

            <div class="box-header with-border">
              <h3 class="box-title">作者信息</h3>
              <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
              </div>
            </div>
            <!-- /.box-header -->

            <div class="box-body">
                <form method="post"  class="form-horizontal">
                    <div class="form-group"><label class="col-sm-2 control-label">作者：</label>
                        <div class="col-sm-8">
			    <input type="text" name="name" value="{{author.name}}" class="form-control" required="">
                       </div>
                    </div>
                           
                    <div class="hr-line-dashed"></div>
                    <div class="form-group"><label class="col-sm-2 control-label">邮箱：</label>
                       <div class="col-sm-8">
			   <input type="text" name="email" value="{{author.email}}" class="form-control" required="">
                       </div>
                    </div>

                    <div class="hr-line-dashed"></div>
                    <div class="form-group"><label class="col-sm-2 control-label">手机：</label>
                       <div class="col-sm-8">
			   <input type="text" name="phone" value="{{author.phone}}" class="form-control" required="">
                       </div>
                    </div>

                    <div class="hr-line-dashed"></div>
                    <div class="form-group"><label class="col-sm-2 control-label">地址：</label>
                       <div class="col-sm-8">
			   <input type="text" name="address" value="{{author.address}}" class="form-control" required="">
                       </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-4 col-sm-offset-2">
                            <button id="delete_button" class="btn btn-danger">删除</button>
                            <button id="submit_button" class="btn btn-primary" type="submit">更新</button>
                        </div>
                    </div>
             </form>
    </div>
    <!-- /.body -->
   </div>
  <!-- /.box -->
</div>
<!-- /.col -->
</div>
<!-- /.row -->



{% endblock %}

{% block js %}
/*删除*/
$("#delete_button").on('click',function(){
    if(confirm("是否确认删除？")){
        $.ajax({
            url:"",
            type: "DELETE",
            success: function(res){
            console.log(res) 
            if (res.code == 0) {
		    swal({
			 "title": "删除",
			 "text": res.result,
			 "type": "success"
		    }, function () {
			 setTimeout(function () {
			   window.location.href="{% url 'books:author_list' %}";
			 }, 50);
		     })
		}else{
			swal("操作失败", res.errmsg, "error")
		     }
	   }
        })

    }  // end confirm
     return false
})


{% endblock %}

templates/books/author_list.html
{% extends "base.html" %}

{% block title %}作者管理{% endblock %}


{% block breadcrunb %}
  <h1>
     Dashboard
    <small>Version 2.0</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">作者列表</li>
  </ol>
{% endblock %}



{% block content %}

<!-- Main row -->
<div class="row">
<!-- Left col -->
<div class="col-md-12">

{% include "authoraddmodel.html" %}


<!-- TABLE: LATEST ORDERS -->
<div class="box box-info">


    <div class="box-header with-border">
      <h3 class="box-title">作者列表</h3>
      <div class="box-tools pull-right">
        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
        </button>
        <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
      </div>
    </div>
    <!-- /.box-header -->

    <div class="box-body">

     <div style="margin-bottom: 10px;height: 30px" class="row">
       <a style="float: left; margin-left: 1%" class="btn btn-sm btn-primary" id = "addbtn"> 添加作者</a>
        <form style="float: right;width: 20%;margin-right: 1%">
        <div  class="input-group">
            <input type="text" class="form-control" name="keyword"
                 placeholder="姓名|email|地址" value="{% if keyword %} {{ keyword }} {% endif %}">
            <div class="input-group-btn">
               <button id='search_btn' type="submit" class="btn btn-sm btn-primary">搜索</button>
            </div>
        </div>
        </form>
     </div>


    <div class="table-responsive">
    <table class="table table-bordered table-striped footable toggle-arrow-tiny" data-page-navigation=".paginations">
        <thead>
	  <tr>
	      <th>姓名</th>
	      <th>书</th>
	      <th>邮箱</th>
	      <th>电话</th>
	      <th>地址</th>
	      <th>操作</th>
	  </tr>
	  </thead>
	  <tbody>
	    {% for author in author_list %}
		<tr>
		    <td> <a href="{% url 'books:author_detail'  author.id %}">{{ author.name }}</a> </td>
		    <td>
			{% for book in author.book_set.all %}
			 < {{ book.name }}>
			{% endfor %}
		    </td>
		    <td> {{ author.email }}</td>
		    <td> {{ author.phone }}</td>
		    <td> {{ author.address }}</td>
		    <td>
			<a type="button" class="btn btn-info btn-xs"  href="{% url 'books:author_detail'  author.id %}" >修改</a>
		    </td>
		</tr>
	    {% endfor %}
	  </tbody>
    </table>

    </div><!-- /.table-responsive -->

    <div class="row">
      <div class="col-sm-6">
	 <div class="dataTables_info" id="editable_info" role="status" aria-live="polite">
	     显示 [{{ paginator.count }}] 条数据中的 第 [{{ page_obj.start_index}}] 至 [{{ page_obj.end_index }}] 的数据
	 </div>
      </div>

      {% include 'paginator.html' %}
    </div><!-- /.paginator -->

</div>
<!-- /.box-body -->

</div>
  <!-- /.box -->
</div>
<!-- /.col -->
</div>
<!-- /.row -->


{% endblock %}

{% block js %}
/*添加用户模态窗弹出*/
$("#addbtn").click(function(){
    $("#author_add_modal").modal("show");
});

/*添加出版商*/
$("#submit_button").click(function(){
    var formdata = $('#AddForm').serialize()
    console.log(formdata)
    $.post('', formdata, function(res){
        console.log(res)
        if (res.code == 0) {
            swal({
                "title": "添加成功",
                 "text": res.result,
                 "type": "success"
            }, function () {
                 setTimeout(function () {
                    window.location.reload();
                 }, 50);
             })
        } else {
            swal("操作失败", res.errmsg, "error");
         }
    })
    return false;
})


{% endblock %}

templates/books/book1_detail.html
{% extends "base.html" %}

  {% block title %}图书信息{% endblock %}
  {% block breadcrunb %}
      <h1>
         Dashboard
        <small>Version 2.0</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">图书信息</li>
      </ol>
  {% endblock %}


{% block content %}

<div class="row">
      <!-- Left col -->
        <div class="col-md-12">
        <div class="box box-info">

            <div class="box-header with-border">
              <h3 class="box-title">图书信息</h3>
              <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
              </div>
            </div>
            <!-- /.box-header -->

            <div class="box-body">
                <form method="post"  class="form-horizontal">
                    <div class="form-group"><label class="col-sm-2 control-label">图书：</label>
                        <div class="col-sm-8">
			    <input type="text" name="name" value="{{book.name}}" class="form-control" required="">
                       </div>
                    </div>
                           
                    <div class="hr-line-dashed"></div>
                    <div class="form-group"><label class="col-sm-2 control-label">作者：</label>
                       <div class="col-sm-8">
                           <select data-placeholder="" multiple="multiple" tabindex="3" name="authors" id="authors"  class="select2 form-control ">
                                {% for author in authors %}
                                    <option value="{{ author.id }}">{{ author.name }}</option>
                              {% endfor %}    
                           </select>
                       </div>
                    </div>

                    <div class="hr-line-dashed"></div>
                    <div class="form-group"><label class="col-sm-2 control-label">出版商：</label>
                       <div class="col-sm-8">
                                <select data-placeholder=""  tabindex="3" name="publisher"  class="select2 form-control ">
                                {% for publish in publishs %}
				   {% if publish  == book.publisher  %}
                                     <option value="{{ publish.id }}" selected="selected">{{ publish.name}}</option>           
                                   {% else %}
                                     <option value="{{ publish.id }}">{{ publish.name }}</option>
                                  {% endif %}
                                {% endfor %}    
                               </select>
                       </div>
                    </div>

                    <div class="hr-line-dashed"></div>
                    <div class="form-group"><label class="col-sm-2 control-label">出版时间：</label>
                       <div class="col-sm-8">
			   <input type="text" name="publication_date" value="{{book.publication_date|date:'Y-m-d'}}" class="form-control datepicker" required="">
                       </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-4 col-sm-offset-2">
                            <button id="delete_button" class="btn btn-danger">删除</button>
                            <button id="submit_button" class="btn btn-primary" type="submit">更新</button>
                        </div>
                    </div>
             </form>
    </div>
    <!-- /.body -->
   </div>
  <!-- /.box -->
</div>
<!-- /.col -->
</div>
<!-- /.row -->



{% endblock %}

{% block js %}

$(".select2").select2({
  width: '100%'
});

$("#authors").select2().val({{ author_list|safe }}).trigger("change")



$('.datepicker').datepicker({
    language: 'zh-CN',
    autoclose: true,
    format: 'yyyy-mm-dd',
    endDate: '0d'
});

/*删除*/
$("#delete_button").on('click',function(){
    if(confirm("是否确认删除？")){
        $.ajax({
            url:"",
            type: "DELETE",
            success: function(res){
            console.log(res) 
            if (res.code == 0) {
		    swal({
			 "title": "删除",
			 "text": res.result,
			 "type": "success"
		    }, function () {
			 setTimeout(function () {
			   window.location.href="{% url 'books:book_list' %}";
			 }, 50);
		     })
		}else{
			swal("操作失败", res.errmsg, "error")
		     }
	   }
        })

    }  // end confirm
     return false
})


{% endblock %}

templates/books/book_detail.html
{% extends "base.html" %}

  {% block title %}图书信息{% endblock %}
  {% block breadcrunb %}
      <h1>
         Dashboard
        <small>Version 2.0</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">图书信息</li>
      </ol>
  {% endblock %}


{% block content %}

<div class="row">
      <!-- Left col -->
        <div class="col-md-12">
        <div class="box box-info">

            <div class="box-header with-border">
              <h3 class="box-title">图书信息</h3>
              <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
              </div>
            </div>
            <!-- /.box-header -->

            <div class="box-body">
                <form method="post"  class="form-horizontal">
                    <div class="form-group"><label class="col-sm-2 control-label">图书：</label>
                        <div class="col-sm-8">
			    <input type="text" name="name" value="{{book.name}}" class="form-control" required="">
                       </div>
                    </div>
                           
                    <div class="hr-line-dashed"></div>
                    <div class="form-group"><label class="col-sm-2 control-label">作者：</label>
                       <div class="col-sm-8">
                                <select data-placeholder="" multiple="multiple" tabindex="3" name="authors"  class="select2 form-control ">
                                {% for author in authors %}
                                   {% for a in book.authors.all %}
				                     {% if author == a  %}
                                     <option value="{{ author.id }}" selected="selected">{{ author.name}}</option>           
                                  {% endif %}
                                  {% endfor %}
                                 <option value="{{ author.id }}">{{ author.name }}</option>
                              {% endfor %}    
                              </select>
                       </div>
                    </div>

                    <div class="hr-line-dashed"></div>
                    <div class="form-group"><label class="col-sm-2 control-label">出版商：</label>
                       <div class="col-sm-8">
                                <select data-placeholder=""  tabindex="3" name="publisher"  class="select2 form-control ">
                                {% for publish in publishs %}
				   {% if publish  == book.publisher  %}
                                     <option value="{{ publish.id }}" selected="selected">{{ publish.name}}</option>           
                                   {% else %}
                                     <option value="{{ publish.id }}">{{ publish.name }}</option>
                                  {% endif %}
                                {% endfor %}    
                               </select>
                       </div>
                    </div>

                    <div class="hr-line-dashed"></div>
                    <div class="form-group"><label class="col-sm-2 control-label">出版时间：</label>
                       <div class="col-sm-8">
			   <input type="text" name="publication_date" value="{{book.publication_date|date:'Y-m-d'}}" class="form-control datepicker" required="">
                       </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-4 col-sm-offset-2">
                            <button id="delete_button" class="btn btn-danger">删除</button>
                            <button id="submit_button" class="btn btn-primary" type="submit">更新</button>
                        </div>
                    </div>
             </form>
    </div>
    <!-- /.body -->
   </div>
  <!-- /.box -->
</div>
<!-- /.col -->
</div>
<!-- /.row -->



{% endblock %}

{% block js %}

$(".select2").select2({
  width: '100%'
});

$('.datepicker').datepicker({
    language: 'zh-CN',
    autoclose: true,
    format: 'yyyy-mm-dd',
    endDate: '0d'
});

/*删除*/
$("#delete_button").on('click',function(){
    if(confirm("是否确认删除？")){
        $.ajax({
            url:"",
            type: "DELETE",
            success: function(res){
            if (res.code == 0) {
		    swal({
			 "title": "删除",
			 "text": res.result,
			 "type": "success"
		    }, function () {
			 setTimeout(function () {
			   window.location.href="{% url 'books:book_list' %}";
			 }, 50);
		     })
		}else{
			swal("操作失败", res.errmsg, "error")
		     }
	   }
        })

    }  // end confirm
     return false
})


{% endblock %}

templates/books/book_list.html
{% extends "base.html" %}

{% block title %}图书管理{% endblock %}


{% block breadcrunb %}
  <h1>
     Dashboard
    <small>Version 2.0</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">图书列表</li>
  </ol>
{% endblock %}



{% block content %}

<!-- Main row -->
<div class="row">
<!-- Left col -->
<div class="col-md-12">

{% include "bookaddmodel.html" %}


<!-- TABLE: LATEST ORDERS -->
<div class="box box-info">


    <div class="box-header with-border">
      <h3 class="box-title">图书列表</h3>
      <div class="box-tools pull-right">
        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
        </button>
        <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
      </div>
    </div>
    <!-- /.box-header -->

    <div class="box-body">

     <div style="margin-bottom: 10px;height: 30px" class="row">
       <a style="float: left; margin-left: 1%" class="btn btn-sm btn-primary" id = "addbtn"> 添加图书 </a>
       <a style="float: left; margin-left: 1%" class="btn btn-sm btn-success" href="{% url 'books:book_add' %}"> 添加图书2 </a>
        <form style="float: right;width: 20%;margin-right: 1%">
        <div  class="input-group">
            <input type="text" class="form-control" name="keyword"
                 placeholder="书名|作者|出版商" value="{% if keyword %} {{ keyword }} {% endif %}">
            <div class="input-group-btn">
               <button id='search_btn' type="submit" class="btn btn-sm btn-primary">搜索</button>
            </div>
        </div>
        </form>
     </div>


    <div class="table-responsive">
    <table class="table table-bordered table-striped footable toggle-arrow-tiny" data-page-navigation=".paginations">
        <thead>
	  <tr>
	      <th>图书</th>
	      <th>作者</th>
	      <th>出版商</th>
	      <th>出版时间</th>
	      <th>操作</th>
	  </tr>
	  </thead>
	  <tbody>
	    {% for book in book_list %}
		<tr>
		    <td> <a href="{% url 'books:book_detail'  book.id %}">{{ book.name }}</a> </td>
		    <td>
			{% for author in book.authors.all %}
			 {{ author.name }},
			{% endfor %}
		    </td>
		    <td> {{ book.publisher.name }}</td>
		    <td> {{ book.publication_date }}</td>
		    <td>
			<a type="button" class="btn btn-info btn-xs"  href="{% url 'books:book_detail'  book.id %}" >修改</a>
		    </td>
		</tr>
	    {% endfor %}
	  </tbody>
    </table>

    </div><!-- /.table-responsive -->

    <div class="row">
      <div class="col-sm-6">
	 <div class="dataTables_info" id="editable_info" role="status" aria-live="polite">
	     显示 [{{ paginator.count }}] 条数据中的 第 [{{ page_obj.start_index}}] 至 [{{ page_obj.end_index }}] 的数据
	 </div>
      </div>

      {% include 'paginator.html' %}
    </div><!-- /.paginator -->

</div>
<!-- /.box-body -->

</div>
  <!-- /.box -->
</div>
<!-- /.col -->
</div>
<!-- /.row -->


{% endblock %}

{% block js %}

$(".select2").select2({
  width: '100%'
});

$('.datepicker').datepicker({
    language: 'zh-CN',
    autoclose: true,
    format: 'yyyy-mm-dd',
    endDate: '0d'
});


/*添加模态窗弹出*/
$("#addbtn").click(function(){
    $("#book_add_modal").modal("show");
});

/*添加图书*/
$("#submit_button").click(function(){
    var formdata = $('#AddForm').serialize()
    console.log(formdata)
    $.post('', formdata, function(res){
        console.log(res)
        if (res.code == 0) {
            swal({
                "title": "添加成功",
                 "text": res.result,
                 "type": "success"
            }, function () {
                 setTimeout(function () {
                    window.location.reload();
                 }, 50);
             })
        } else {
            swal("操作失败", res.errmsg, "error");
         }
    })
    return false;
})


{% endblock %}

templates/books/publish_list.html
{% extends "base.html" %}

{% block title %}出版商管理{% endblock %}


{% block breadcrunb %}
  <h1>
     Dashboard
    <small>Version 2.0</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">出版商列表</li>
  </ol>
{% endblock %}



{% block content %}

<!-- Main row -->
<div class="row">
<!-- Left col -->
<div class="col-md-12">

{% include "publishaddmodel.html" %}


<!-- TABLE: LATEST ORDERS -->
<div class="box box-info">


    <div class="box-header with-border">
      <h3 class="box-title">出版商列表</h3>
      <div class="box-tools pull-right">
        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
        </button>
        <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
      </div>
    </div>
    <!-- /.box-header -->

    <div class="box-body">

     <div style="margin-bottom: 10px;height: 30px" class="row">
       <a style="float: left; margin-left: 1%" class="btn btn-sm btn-primary" id = "addbtn"> 添加出版商 </a>
        <form style="float: right;width: 20%;margin-right: 1%">
        <div  class="input-group">
            <input type="text" class="form-control" name="keyword"
                 placeholder="出版商|地址|城市" value="{% if keyword %} {{ keyword }} {% endif %}">
            <div class="input-group-btn">
               <button id='search_btn' type="submit" class="btn btn-sm btn-primary">搜索</button>
            </div>
        </div>
        </form>
     </div>


    <div class="table-responsive">
    <table class="table table-bordered table-striped footable toggle-arrow-tiny" data-page-navigation=".paginations">
        <thead>
	  <tr>
	      <th>出版社</th>
	      <th>书</th>
	      <th>地址</th>
	      <th>所属城市</th>
	      <th>操作</th>
	  </tr>
	  </thead>
	  <tbody>
	    {% for publish in publish_list %}
		<tr>
		    <td> <a href="{% url 'books:publish_detail'  publish.id %}">{{ publish.name }}</a> </td>
		    <td>
			{% for book in publish.book_set.all %}
			 < {{ book.name }}>
			{% endfor %}
		    </td>
		    <td> {{ publish.city }}</td>
		    <td> {{ publish.address }}</td>
		    <td>
			<a type="button" class="btn btn-info btn-xs"  href="{% url 'books:publish_detail'  publish.id %}" >修改</a>
		    </td>
		</tr>
	    {% endfor %}
	  </tbody>
    </table>

    </div><!-- /.table-responsive -->

    <div class="row">
      <div class="col-sm-6">
	 <div class="dataTables_info" id="editable_info" role="status" aria-live="polite">
	     显示 [{{ paginator.count }}] 条数据中的 第 [{{ page_obj.start_index}}] 至 [{{ page_obj.end_index }}] 的数据
	 </div>
      </div>

      {% include 'paginator.html' %}
    </div><!-- /.paginator -->

</div>
<!-- /.box-body -->

</div>
  <!-- /.box -->
</div>
<!-- /.col -->
</div>
<!-- /.row -->


{% endblock %}

{% block js %}
/*添加用户模态窗弹出*/
$("#addbtn").click(function(){
    $("#publish_add_modal").modal("show");
});

/*添加出版商*/
$("#submit_button").click(function(){
    var formdata = $('#AddForm').serialize()
    console.log(formdata)
    $.post('', formdata, function(res){
        console.log(res)
        if (res.code == 0) {
            swal({
                "title": "添加成功",
                 "text": res.result,
                 "type": "success"
            }, function () {
                 setTimeout(function () {
                    window.location.reload();
                 }, 50);
             })
        } else {
            swal("操作失败", res.errmsg, "error");
         }
    })
    return false;
})


{% endblock %}