apps/dashboard/urls.py
from django.conf.urls import include, url
from dashboard import users, role, power

urlpatterns = [
    url(r'^userlist/$', users.UserListView.as_view(), name='user_list'),
    url(r'^userdetail/(?P<pk>[0-9]+)?/$', users.UserDetailView.as_view(), name='user_detail'),
    url(r'^modifypasswd/$', users.ModifyPwdView.as_view(), name='modify_pwd'),
    url(r'^usergrouppower/(?P<pk>[0-9]+)?/$', users.UserGroupPowerView.as_view(), name='user_group_power'),

    url(r'^grouplist/$', role.GroupListView.as_view(), name='role_list'),
    url(r'^groupdetail/(?P<pk>[0-9]+)?/$', role.GroupDetailView.as_view(), name='role_detail'),
    url(r'^groupusers/$', role.GroupUsersView.as_view(), name='role_users'),


    url(r'^powerlist/$', power.PowerListView.as_view(), name='power_list'),
    url(r'^powerdetail/(?P<pk>[0-9]+)?/$', power.PowerDetailView.as_view(), name='power_detail'),

]

opsweb/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from dashboard.views import LoginView, LogoutView, IndexView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^$', IndexView.as_view(), name='index'),
    url('^index/', IndexView.as_view(), name='index'),
    url('^login/', LoginView.as_view(), name='login'),
    url('^logout/', LogoutView.as_view(), name='logout'),
    url('^dashboard/', include("dashboard.urls", namespace="dashboard")),
    url('^work_order/', include('work_order.urls', namespace='work_order')),
    url('^cmdb/', include('cmdb.urls', namespace='cmdb')),
    url('^task/', include('tasks.urls', namespace='task')),
    url('^books/', include('books.urls', namespace='books')),
    url('^projects/', include('projects.urls', namespace='projects')),
    url('^deploy/', include('code_release.urls', namespace='deploy')),
]

apps/dashboard/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import AbstractUser


class UserProfile(AbstractUser):
    name_cn = models.CharField('中文名', max_length=30)
    phone = models.CharField('手机', max_length=11, null=True, blank=True)
    GENDER_CHOICES = (
        ('1', u'总监'),
        ('2', u'经理'),
        ('3', u'研发'),
    )
    role = models.CharField(max_length=4, default='3', choices=GENDER_CHOICES)
    note = models.CharField(max_length=128, default='', blank=True)

    class Meta:
        verbose_name = '用户信息'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.role

    def __unicode__(self):
        return self.username

apps/dashboard/forms.py
# _*_ coding: utf-8 _*_

from django import forms
from django.contrib.auth.models import Group, Permission
from .models import UserProfile


class LoginForm(forms.Form):
    username = forms.CharField(required=True)
    password = forms.CharField(required=True)


class UserProfileForm(forms.Form):
    username = forms.CharField(required=True, max_length=30)
    name_cn = forms.CharField(required=True, max_length=30)
    phone = forms.CharField(required=True, max_length=11)
    email = forms.EmailField(required=True, max_length=20)

apps/dashboard/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponseRedirect,JsonResponse
from django.core.urlresolvers import reverse
from django.views.generic import View
from django.contrib.auth import authenticate,login,logout
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django_otp import match_token, user_has_device, devices_for_user


# 自定义模块导入
from .forms import LoginForm


class LoginView(View):
    """
        登录模块
    """
    def get(self, request):
        return render(request, "login.html")

    def post(self, request):
        res = {"code": 0}
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            username = request.POST.get("username", None)
            password = request.POST.get("password", None)
            # token = request.POST.get('token', None)
            user = authenticate(username=username, password=password)
            # mttoken = match_token(user, token)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    res['next_url'] = '/'
                else:
                    res['code'] = 1
                    res['errmsg'] = '用户被禁用'
            else:
                res['code'] = 1
                res['errmsg'] = '用户名或密码错误'
            # if mttoken is None:# 验证动态码
            #     res['code'] = 1
            #     res['errmsg'] = '动态口令错误'
        else:
            res['code'] = 1
            res['errmsg'] = "用户名或密码不能为空"
        return JsonResponse(res, safe=True)


class LogoutView(LoginRequiredMixin,View):
    """
        登出

        关于用户登录验证两种方式：
        1：基于全类所有方法生效的可以利用LoginRequiredMixin
        2：基于类里面某个函数的可以用login_required
    """
    # @method_decorator(login_required)
    def get(self, request):
        logout(request)
        return HttpResponseRedirect(reverse("login"))


class IndexView(View):
    """
        首页
    """
    @method_decorator(login_required(login_url="login"))
    def get(self, request):
        return render(request, 'index.html')

templates/dashboard/change_passwd.html
{% extends "base.html" %}

  {% block title %}密码修改{% endblock %}

  {% block breadcrunb %}
      <h1>
         Dashboard
        <small>Version 2.0</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">修改密码</li>
      </ol>
  {% endblock %}



{% block content %}

<div class="row">
<!-- Left col -->
<div class="col-md-12">
<div class="box box-info">

         <div class="box-header with-border">
          <h3 class="box-title">修改密码</h3>
          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
            </button>
            <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
          </div>
        </div>
        <!-- /.box-header -->


       <div class="box-body">
          {% if msg %}
            <div class="alert alert-danger">{{ msg }}</div>
          {% endif %}
          <form class="form-horizontal" action="{% url 'dashboard:modify_pwd' %}" method="post">
                <input type="hidden" name="uid" value="{{ uid }}">
                <div class="form-group">
                    <label class="col-sm-2 control-label">新密码：</label>
                    <div class="col-sm-6">
                        <input type="password" name="password1" placeholder="新密码" class="form-control" required="">
                    </div>
                </div>
                <div class="hr-line-dashed"></div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">确认密码：</label>
                    <div class="col-sm-6">
                        <input type="password" name="password2" placeholder="确认密码" class="form-control" required="">
                    </div>
                </div>

                <div class="hr-line-dashed"></div>
                <div class="form-group">
                    <div class="col-sm-4 col-sm-offset-2">
                        <button class="btn btn-white" type="reset" href="{% url 'dashboard:user_list' %}">取消</button>
                         <button type="submit" class="btn btn-primary block full-width m-b">确定</button>
                    </div>
                </div>
        </form>
    </div>

</div>
</div>
</div>

{% endblock %}

templates/dashboard/group_list.html
{% extends "base.html" %}

{% load mytags %}
  {% block title %}首页{% endblock %}
  {% block css %}
  <style>
    .form-horizontal .form-group{margin-bottom:10px;width:100%;}
    .form-horizontal  .form-control{width:86%;}
    .form-horizontal .control-label{width:75px;}
  </style>

  {% endblock %}

  {% block breadcrunb %}
      <h1>
         Dashboard
        <small>Version 2.0</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">角色管理</li>
      </ol>
  {% endblock %}



{% block content %}

      <!-- Main row -->
      <div class="row">
        <!-- Left col -->
        <div class="col-md-12">

        {% include "groupaddmodel.html" %}
        <!-- TABLE: LATEST ORDERS -->
        <div class="box box-info">


            <div class="box-header with-border">
              <h3 class="box-title">角色列表</h3>
              <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
              </div>
            </div>
            <!-- /.box-header -->

            <div class="box-body">

             <div style="margin-bottom: 10px;height: 30px" class="row">
                <a style="float: left; margin-left: 1%" class="btn btn-sm btn-primary" id = "addbtn"> 添加角色 </a>
                <form style="float: right;width: 20%;margin-right: 1%">
                <div  class="input-group">
                    <input type="text" class="form-control" name="keyword"
                         placeholder="角色名" value="{% if keyword %} {{ keyword }} {% endif %}">
                    <div class="input-group-btn">
                       <button id='search_btn' type="submit" class="btn btn-sm btn-primary">搜索</button>
                    </div>
                </div>
                </form>
             </div>


        <!--组列表部分-->
        <div class="table-responsive">
            <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th class="text-center">组名</th>
                    <th class="text-center">组员</th>
                    <th class="text-center">权限</th>
                    <th class="text-center">操作</th>
                </tr>
            </thead>
            <tbody>
            {% for group in grouplist %}
                <tr class="gradeX">
                    <td class="text-center">{{ group.name }}</td>
                    <td class="text-center"> {{ group.user_set.all | userlist_str2| default:'无' }}
                    <a class="btn btn-xs btn-info more" gid="{{group.id}}" gname="{{group.name}}">更多</a>
                    </td>
                    <td class="text-center"> {{ group.permissions.all | group_str2 | default:'无'  }} </td>
                    <td class="text-center">
                       <div class="btn-group">
                            <button class="btn btn-primary btn-sm dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="false">
                                编辑
                                 <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                                 <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url 'dashboard:role_detail' group.id %}">角色管理</a></li>
                            </ul>                                                                                                                                                        
                        </div>
                         <a href="#" class="btn btn-xs btn-danger delete" data-id = {{ group.id }} >删除</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        </div><!-- /.table-responsive -->

            <div class="row">
              <div class="col-sm-6">
                 <div class="dataTables_info" id="editable_info" role="status" aria-live="polite">
                     显示 [{{ paginator.count }}] 条数据中的 第 [{{ page_obj.start_index}}] 至 [{{ page_obj.end_index }}] 的数据
                 </div>
              </div>
              {% include 'paginator.html' %}
            </div><!-- /.paginator -->

            </div>
            <!-- /.box-body -->

        </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->

{% endblock %}

{% block js %}

/*POST请求*/
function post(group_value){
    if (group_value == ""){
        swal("添加失败", "用户组名不能为空", 'error');
        return false;
    }
    $.post("", {"name": group_value},function(res){
        if(res.code==0){
            swal({
                "title": "添加成功",
                "text": "",
                "type": "success"
            },function(){
                setTimeout(function(){
                    window.location.reload();
                },50);
            })
        }else{
            swal("操作失败", res.errmsg, "error");
        }
    })

}

/*执行添加用户组*/
$("#addbtn").click(function(){
    $("#add_group_model").modal("show");
    $("#create_group_btn").click(function(){
        var group_value = $("#form_groupname").val();
        $("#add_group_model").modal("hide");
        post(group_value)
    })
});


/*删除组*/
$("tbody").on('click','.delete',function(){
    if(confirm("是否确认删除组？")){
        var that = this;
        var id = $(this).attr('data-id')
        $.ajax({
            url:"",
            type: "DELETE",
            data: {"id":id},
            datatype: "json",
            success: function(res){
                console.log(res)
                if (res.code ==0){
                    swal({
                    "title": "删除成功",
                    "text": "",
                    "type": "success"
                    },function(){
                        setTimeout(function(){
                            window.location.reload();
                },50);
            })
                }else{
                    swal("操作失败", res.errmsg, "error")
                }
            }
        })         

    }  // end confirm
     return false   //get data and end
})



/*组与组成员关系模态窗*/
$(".more").click(function(){
  $("#group_users_model").modal("show");
  var gid=$(this).attr('gid');
  var gname=$(this).attr('gname');
  // 展示组内成员
  $.get("/dashboard/groupusers/", {"gid": gid},function(res){
        var html = '<table class="table table-striped">';
        $.each(res, function(n, obj){
            html += '<tr>';
            html += '<td>'+obj.username+'</td>';
            html += '<td>'+obj.name_cn+'</td>';
            html += '<td>'+obj.email+'</td>';
            html += '<td><button class="btn btn-danger btn-xs del_group_user" uid="'+obj.id+'">删除</button></td>';
            html += '</tr>'
        });
        html += '</table>';
        $("#modal_show_group_users_list_title").html(gname);
        $("#modal_show_group_users_content_list").html(html);

  // 删除组内成员
  $(".del_group_user").click(function(){
        var that = $(this);
        var uid = that.attr('uid');
        $.ajax({
            url:"/dashboard/groupusers/",
            type: "DELETE",
            data: {"groupid": gid, "userid": uid},
            datatype: "json",
            success: function(res){
                if (res.code == 0){
                    that.parents("tr").remove();
                }else{
                    swal("操作失败", res.errmsg, "error")
                }
            }
        })  // end ajax
     });    // end del
  });   // end get
})

{% endblock %}

templates/dashboard/power_edit.html
{% extends "base.html" %}

  {% block title %}用户更新{% endblock %}
  {% block breadcrunb %}
      <h1>
         Dashboard
        <small>Version 2.0</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">权限更新</li>
      </ol>
  {% endblock %}


{% block content %}

<div class="row">
      <!-- Left col -->
        <div class="col-md-12">

        <div class="box box-info">


            <div class="box-header with-border">
              <h3 class="box-title">权限更新</h3>
              <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
              </div>
            </div>
            <!-- /.box-header -->

            <div class="box-body">
                    <form method="post"  class="form-horizontal">
                    <input type="hidden" name="id" value="{{power.id}}">
                    <div class="form-group">
                        <label class="col-sm-2 control-label">权限名：</label>
                        <div class="col-sm-8">
                            <input type="text" name="codename" value="{{power.codename}}" class="form-control" required="">
                        </div>
                    </div>
                           
                    <div class="hr-line-dashed"></div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">权限描述：</label>
                       <div class="col-sm-8">
                           <input type="text" name="name" value="{{power.name}}" class="form-control" required="">
                       </div>
                    </div>

                    <div class="hr-line-dashed"></div>
                    <div class="form-group">
                        <div class="col-sm-4 col-sm-offset-2">
                            <button class="btn btn-white" type="reset" href="{% url 'dashboard:power_list' %}">取消</button>
                            <button id="submit_button" class="btn btn-primary" type="submit">确认</button>
                        </div>
                    </div>
                    </form>


        </div>
    <!-- /.body -->
   </div>
  <!-- /.box -->
</div>
<!-- /.col -->
</div>
<!-- /.row -->

{% endblock %}

{% block js %}
{% endblock %}

templates/dashboard/user_edit.html
{% extends "base.html" %}

  {% block title %}用户更新{% endblock %}
  {% block breadcrunb %}
      <h1>
         Dashboard
        <small>Version 2.0</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">用户更新</li>
      </ol>
  {% endblock %}


{% block content %}

<div class="row">
      <!-- Left col -->
        <div class="col-md-12">

        <div class="box box-info">


            <div class="box-header with-border">
              <h3 class="box-title">用户更新</h3>
              <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
              </div>
            </div>
            <!-- /.box-header -->

            <div class="box-body">

                <div style="margin-bottom: 10px;height: 30px" class="row">
                    <a style="float: right; margin-right: 1%" class="btn btn-sm btn-primary"
                       href="{% url 'dashboard:modify_pwd' %}?uid={{ user.id }}"> 修改密码 </a>
                </div>


                <form method="post"  class="form-horizontal">
                    <input type="hidden" name="id" value="{{user.id}}">
                    <div class="form-group"><label class="col-sm-2 control-label">用户名：</label>
                        <div class="col-sm-8"><input type="text" readonly="readonly" name="username" value="{{user.username}}" class="form-control" required=""></div>
                    </div>
                           
                    <div class="hr-line-dashed"></div>
                    <div class="form-group"><label class="col-sm-2 control-label">中文名：</label>
                       <div class="col-sm-8"><input type="text" name="name_cn" value="{{user.name_cn}}" class="form-control" required=""></div>
                    </div>

                    <div class="hr-line-dashed"></div>
                    <div class="form-group"><label class="col-sm-2 control-label">手机：</label>
                       <div class="col-sm-8"><input type="text" name="phone" value="{{user.phone}}" class="form-control" required=""></div>
                    </div>

                    <div class="hr-line-dashed"></div>
                    <div class="form-group"><label class="col-sm-2 control-label">邮箱：</label>
                       <div class="col-sm-8"><input type="text" name="email" value="{{user.email}}" class="form-control" required=""></div>
                    </div>

                    <div class="hr-line-dashed"></div>
                    <div class="form-group">
                        <div class="col-sm-4 col-sm-offset-2">
                            <button class="btn btn-white" type="reset" href="{% url 'dashboard:user_list' %}">取消</button>
                            <button id="submit_button" class="btn btn-primary" type="submit">确认</button>
                        </div>
                    </div>
                    </form>
    </div>
    <!-- /.body -->
   </div>
  <!-- /.box -->
</div>
<!-- /.col -->
</div>
<!-- /.row -->



{% endblock %}

{% block js %}
{% endblock %}

templates/dashboard/user_group.html
{% extends 'public/layout.html' %}


{% block breadcrumb %}
     <ol class="breadcrumb">
        <li>
            <a href="{% url 'index' %}">首页</a>
        </li>
         <li>
             <a>用户管理</a>
         </li>
        <li class="active">
            <strong>用户权限管理</strong>
         </li>
    </ol>
{% endblock %}
{% block body %}
<div class="row">
    <div class="col-lg-10">
        <div class="ibox float-e-margins">
            <h5>用户组管理</h5>

            <div class="ibox-content">
                 <form method="post" action="{% url 'user_group' %}" class="form-horizontal">
                        <input type="hidden" value='{{uid}}' name="uid">  <!--update need id-->

                        <div class="hr-line-dashed"></div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">权限：</label>
                            <!--待选择区域-->
                            <div class="col-sm-4">
                                <select id="groups" name ="groups" class="form-control m-b" multiple size="12">
                                {% for group in user_not_groups %}
                                    <option value="{{ group.id }}" >{{ group.name }}</option>
                                {% endfor %}
                                </select> 
                            </div>

                            <!--中间选择箭头-->
                            <div class="col-sm-1">
                                <div class=" btn-group" style="margin-top: 70px;">
                                     <button type="button" class="btn btn-white" onclick="move('groups', 'groups_selected')"><i class="fa fa-chevron-right"></i></button>
                                    <button type="button" class="btn btn-white" onclick="move('groups_selected', 'groups')"><i class="fa fa-chevron-left"></i> </button>
                                </div> 
                            </div>

                            <!--x选中区域-->
                            <div class="col-sm-3">
                                     <div>
                                         <select id="groups_selected" name="groups_selected" class="form-control m-b" size="12"  multiple>
                                             {% for group in user_has_groups %}
                                            <option value="{{ group.id }}" >{{ group.name }}</option>
                                            {% endfor %}                                                                       
                                         </select>
                                    </div> 
                            </div>
                         </div> <!--end form-group-->


                       <div class="hr-line-dashed"></div>
                       <div class="form-group">
                             <div class="col-sm-4 col-sm-offset-2">
                                 <button class="btn btn-white" type="reset" href="{% url 'dashboard:user_list' %}">取消</button>
                                 <button id="submit_button" class="btn btn-primary" type="submit">确认</button>
                            </div>  
                       </div>
                </form>
            </div>


        </div>
    </div>
</div>
{% endblock %}
{% block js %}
<script>
function move(from, to, from_o, to_o) {
    $("#" + from + " option").each(function () {
        if ($(this).prop("selected") == true) {
            $("#" + to).append(this);
            if( typeof from_o !== 'undefined'){
                $("#"+to_o).append($("#"+from_o +" option[value='"+this.value+"']"));
            }
          }
    });
}

</script>
{% endblock %}

templates/dashboard/user_list.html
{% extends "base.html" %}
{% load mytags %} }}
  {% block title %}首页{% endblock %}
  {% block css %}
  <style>
    .form-horizontal .form-group{margin-bottom:10px;width:100%;}
    .form-horizontal  .form-control{width:86%;}
    .form-horizontal .control-label{width:75px;}
  </style>

  {% endblock %}

  {% block breadcrunb %}
      <h1>
         Dashboard
        <small>Version 2.0</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">个人中心</li>
      </ol>
  {% endblock %}



{% block content %}


      <!-- Main row -->
      <div class="row">
        <!-- Left col -->
        <div class="col-md-12">

        {% include "useraddmodel.html" %}
        <!-- TABLE: LATEST ORDERS -->
        <div class="box box-info">


            <div class="box-header with-border">
              <h3 class="box-title">用户列表</h3>
              <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
              </div>
            </div>
            <!-- /.box-header -->

            <div class="box-body">

             <div style="margin-bottom: 10px;height: 30px" class="row">
                <a style="float: left; margin-left: 1%" class="btn btn-sm btn-primary" id = "addbtn"> 添加用户 </a>
                <form style="float: right;width: 20%;margin-right: 1%">
                <div  class="input-group">
                    <input type="text" class="form-control" name="keyword"
                         placeholder="用户名|姓名" value="{% if keyword %} {{ keyword }} {% endif %}">
                    <div class="input-group-btn">
                       <button id='search_btn' type="submit" class="btn btn-sm btn-primary">搜索</button>
                    </div>
                </div>
                </form>
             </div>


            <div class="table-responsive">
            <table class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th class="text-center">用户名</th>
                    <th class="text-center">姓名</th>
                    <th class="text-center">小组</th>
                    <th class="text-center">手机</th>
                    <th class="text-center">激活</th>
                    <th class="text-center">操作</th>
                </tr>
                </thead>
                <tbody>
                 {% for user in userlist %}
                   <tr class="gradeX">
                      <td class="text-center"><a href="{% url 'dashboard:user_detail' user.id %}">{{ user.username }}</a> </td>
                      <td class="text-center"> {{ user.name_cn }} </td>
                      <td class="text-center"> {{ user.groups.all | group_str2 |default:"无"}} </td>
                      <td class="text-center">{{ user.phone | default_if_none:'' }}</td>
                      <td class="text-center">{{ user.is_active }}</td>
                
                      <td class="text-center">
                        <div class="btn-group" >
                         <button class="btn btn-primary btn-sm dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="false">修改<span class="caret"></span></button>
                         <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                            <li role="presentation"><a role="menuitem" tabindex="-1"
                             href="{% url 'dashboard:modify_pwd' %}?uid={{ user.id }}">修改密码</a>
                            </li>

                    
                            <li role="presentation"><a role="menuitem" tabindex="-1"
                              href="{% url 'dashboard:user_group_power' user.id  %}"  class="user_group">角色权限修改</a>
                            </li>
                          </ul>
                        </div>
                        <a class="btn btn-xs btn-danger del" data-id="{{ user.id }}" {% if user.username == 'admin' %} disabled {% endif %}>删除</a>
                       </td>
                   </tr>
                {% endfor %}
                </tbody>
            </table>
            </div><!-- /.table-responsive -->

            <div class="row">
              <div class="col-sm-6">
                 <div class="dataTables_info" id="editable_info" role="status" aria-live="polite">
                     显示 [{{ paginator.count }}] 条数据中的 第 [{{ page_obj.start_index}}] 至 [{{ page_obj.end_index }}] 的数据
                 </div>
              </div>

              {% include 'paginator.html' %}
            </div><!-- /.paginator -->

            </div>
            <!-- /.box-body -->

        </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->


{% endblock %}

{% block js %}

/*添加用户模态窗弹出*/
$("#addbtn").click(function(){
    $("#user_add_modal").modal("show"); 
});

/*添加用户*/
$("#submit_button").click(function(){
    var formdata = $('#AddForm').serialize()
    console.log(formdata)
    $.post('', formdata, function(res){
        if (res.code == 0) {
            swal({ 
                "title": "添加成功",
                 "text": res.result,
                 "type": "success"
            }, function () {
                 setTimeout(function () {
                    window.location.reload();
                 }, 50);
             })
        } else {
            swal("操作失败", res.errmsg, "error");
         }
    })
    return false;
})

/*删除用户*/
$("tbody").on('click','.del',function(){
    if(confirm("是否确认删除？")){
        var that = this;
        var id = $(this).attr('data-id')
        $.ajax({
            url:"",
            type: "DELETE",
            data: {"id":id},
            datatype: "json",
            success: function(res){
                console.log(res)
                if (res.code ==0){
                    swal({
                "title": "删除成功",
                 "text": res.result,
                 "type": "success"
            }, function () {
                 setTimeout(function () {
                    window.location.reload();
                 }, 50);
             })
                }else{
                    swal("操作失败", res.errmsg, "error")
                }
            }
        })

    }  // end confirm
     return false
})


{% endblock %}