apps/tasks/urls.py
from django.conf.urls import  url

from .views import  *

urlpatterns = [
    url('^add/$', TaskAddView.as_view(), name='add'),
    url('^add1/$', TaskAdd1View.as_view(), name='add1'),
    url('^edit/(?P<pk>[0-9]+)?/$', TaskEditView.as_view(), name='edit'),
    url('^list/$', TaskListView.as_view(), name='list'),
    url('^detail/(?P<pk>[0-9]+)?/$', TaskDetailView.as_view(),name='detail'),
]

opsweb/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from dashboard.views import LoginView, LogoutView, IndexView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^$', IndexView.as_view(), name='index'),
    url('^index/', IndexView.as_view(), name='index'),
    url('^login/', LoginView.as_view(), name='login'),
    url('^logout/', LogoutView.as_view(), name='logout'),
    url('^dashboard/', include("dashboard.urls", namespace="dashboard")),
    url('^work_order/', include('work_order.urls', namespace='work_order')),
    url('^cmdb/', include('cmdb.urls', namespace='cmdb')),
    url('^task/', include('tasks.urls', namespace='task')),
    url('^books/', include('books.urls', namespace='books')),
    url('^projects/', include('projects.urls', namespace='projects')),
    url('^deploy/', include('code_release.urls', namespace='deploy')),
]

apps/tasks/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models


class Tasks(models.Model):
    name = models.CharField(max_length=128, verbose_name=u'任务名称')
    playbook = models.FileField(upload_to='playbook/%Y/%m', verbose_name=u'playbook文件')
    detail_result = models.TextField(verbose_name=u'执行结果详情')
    status = models.CharField(max_length=1, choices=(('Y', '已执行'), ('N', '未执行')), default='N', verbose_name='执行状态')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name=u'任务创建时间')
    exec_time = models.DateTimeField(auto_now=True, verbose_name=u'执行时间')

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = u'add_task'
        verbose_name_plural = verbose_name
        ordering = ['-add_time']


class ExecResult(models.Model):
    task = models.ForeignKey(Tasks, verbose_name=u'任务')
    host = models.CharField(max_length=64, verbose_name=u'主机名')
    unreachable = models.IntegerField(verbose_name=u'不可达')
    skipped = models.IntegerField(verbose_name=u'跳过')
    ok = models.IntegerField(verbose_name=u'成功')
    changed = models.IntegerField(verbose_name=u'改变')
    failures = models.IntegerField(verbose_name=u'失败')

    def __unicode__(self):
        return self.task.name

    class Meta:
        verbose_name = u'task_result'
        verbose_name_plural = verbose_name

apps/tasks/forms.py
from django import forms

from  .models import Tasks


class TaskAddForm(forms.ModelForm):
    class Meta:
        model = Tasks
        fields = ['name','playbook']

class TaskAdd1Form(forms.ModelForm):
    playbook_text = forms.CharField(required=True)

    class Meta:
        model = Tasks
        fields = ['name']

apps/tasks/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.http import HttpResponse,HttpResponseRedirect
from django.views.generic import View, TemplateView, ListView, DetailView,CreateView, UpdateView

from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from pure_pagination.mixins import PaginationMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.files.base import ContentFile


from .models import Tasks, ExecResult
from .forms import TaskAddForm,TaskAdd1Form
from utils.ansible_api import AnsiblePlaybookAPI
import logging, traceback,json

logger = logging.getLogger("opsweb")


class TaskAdd1View(LoginRequiredMixin, CreateView):
    template_name = 'tasks/task_add1.html'
    model = Tasks
    form_class = TaskAdd1Form

    def get_success_url(self):
        return reverse('task:list')

    def form_valid(self, form):
        playbook_text = form.cleaned_data['playbook_text']
        form.instance.playbook.save(form.cleaned_data['name'] + '.yml', ContentFile(playbook_text))
        return super(TaskAdd1View, self).form_valid(form)


class TaskEditView(LoginRequiredMixin, UpdateView):
    template_name = 'tasks/task-edit.html'
    model = Tasks
    context_object_name = "task"
    form_class = TaskAdd1Form

    def get_success_url(self):
        return reverse('task:list')

    def form_valid(self, form):
        playbook_text = form.cleaned_data['playbook_text']
        self.object.playbook.delete()
        form.instance.playbook.save(form.cleaned_data['name'] + '.yml', ContentFile(playbook_text))
        return super(TaskEditView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(TaskEditView, self).get_context_data(**kwargs)
        playbook_text = ''
        with open(self.object.playbook.path, 'r') as f:
            for line in f:
                playbook_text += line
        context['playbook_text'] = json.dumps(playbook_text)
        return context


class TaskAddView(LoginRequiredMixin,TemplateView ):
    # def get(self, request):
    #     forms = TaskAddForm()
    #     return render(request, 'tasks/task_add.html', {'forms': forms})

    template_name = "tasks/task_add.html"

    def post(self, request):
        forms = TaskAddForm(request.POST, request.FILES)
        if forms.is_valid():
            forms.save()
            '''
            name = forms.cleaned_data['name']
            playbook = forms.cleaned_data['playbook']
            auto_task = Tasks()
            auto_task.name = name
            auto_task.playbook = playbook
            auto_task.save()
            '''
            return HttpResponseRedirect(reverse('task:list'))
        else:
            return render(request, 'tasks/task_add.html', {'forms': forms, 'errmsg': '表单验证不通过'})


class TaskListView(LoginRequiredMixin, PaginationMixin, ListView):
    """
        任务列表
    """
    model = Tasks
    template_name = 'tasks/tasks_list.html'
    context_object_name = "tasklist"
    paginate_by = 5
    keyword = ''

    def get_queryset(self):
        queryset = super(TaskListView, self).get_queryset()
        self.keyword = self.request.GET.get('keyword', '')
        if self.keyword:
            queryset = queryset.filter(Q(name__icontains=self.keyword)|
                                        Q(detail_result__icontains=self.keyword))
        return queryset

    def get_context_data(self, **kwargs):
        context = super(TaskListView, self).get_context_data(**kwargs)
        context['keyword'] = self.keyword
        return context

    """
        playbook执行
    """

    def post(self, request, *args, **kwargs):
        pk = request.POST.get('task_id', 0)
        task = Tasks.objects.get(pk=int(pk))
        print "path is %s " % task.playbook.path
        try:
            playbook = AnsiblePlaybookAPI(task.playbook.path)
            exec_result = playbook.run()
            task.detail_result = exec_result['detail']
            task.status = 'Y'
            task.save()
        except:
            logger.error("insert Tasks  error: %s" % traceback.format_exc())
            return HttpResponse(json.dumps({'status': 1,'msg': '任务执行失败'}),
                            			content_type="application/json")


        simple = exec_result['simple']
        for record in simple:
            try:
                task_result = ExecResult()
                task_result.task = task
                task_result.host = record
                task_result.unreachable = simple[record]['unreachable']
                task_result.skipped = simple[record]['skipped']
                task_result.ok = simple[record]['ok']
                task_result.changed = simple[record]['changed']
                task_result.failures = simple[record]['failures']
                task_result.save()
            except:
                logger.error("insert ExecResult  error: %s" % traceback.format_exc())
                return HttpResponse(json.dumps({'status': 1,'msg': '任务信息获取失败'}),
                            			content_type="application/json")

        return HttpResponse(json.dumps({'status': 0,
                                        'task_status': task.status,
                                        'task_exec_result': simple,
                                        'msg': '任务执行成功'}),
                            content_type="application/json")


class TaskDetailView(LoginRequiredMixin, DetailView):
    '''
         任务详情
    '''
    template_name = 'tasks/task_detail.html'
    model = Tasks
    context_object_name = 'task'

templates/tasks/task-edit.html
{% extends 'base.html' %}


{% block title %}更新任务{% endblock %}
{% block breadcrunb %}
  <h1>
     Dashboard
    <small>Version 2.0</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">任务更新</li>
  </ol>
{% endblock %}


{% block content %}
<!-- Main row -->
<div class="row">
<!-- Left col -->
<div class="col-md-12">

<!-- TABLE: LATEST ORDERS -->
<div class="box box-info">

<div class="box-header with-border">
  <h3 class="box-title">任务申请</h3>
  <div class="box-tools pull-right">
    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
    </button>
    <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
  </div>
</div>
<!-- /.box-header -->

<div class="box-body">
<form method="post" action="" class="form-horizontal">
        <div class="form-group"><label class="col-sm-2 control-label">任务名称：</label>
            <div class="col-sm-8">
                <input type="text" name ="name" id="name" class="form-control" value="{{ task.name }}" placeholder="任务名称" />
                {% for error in forms.name.errors %}<span class="help-block m-b-none red">{{ error }}</span>{% endfor %}
            </div>
        </div>
        <div class="hr-line-dashed"></div>
        <div class="form-group"><label class="col-sm-2 control-label">脚本编辑：</label>
             <div class="col-sm-8">
                <pre id="code" class="ace_editor" style="min-height:400px"><textarea id="playbook_text" class="ace_text-input" name="playbook_text"></textarea></pre>
             </div>
        </div>
        <div class="hr-line-dashed"></div>
        <div class="form-group">
            <div class="col-sm-4 col-sm-offset-2">
                <button id="submit_button" class="btn btn-primary" type="button">更新任务</button>
                <button class="btn btn-white" type="reset">重置</button>
            </div>
        </div>
    </form>

</div>
</div>
</div>
</div>
{% endblock %}
{% block js %}

//初始化对象
editor = ace.edit("code");

//设置风格和语言（更多风格和语言，请到github上相应目录查看）
theme = "clouds";
language = "yaml";
editor.setTheme("ace/theme/" + theme);
editor.session.setMode("ace/mode/" + language);

//字体大小
editor.setFontSize(18);

//设置只读（true时只读，用于展示代码）
editor.setReadOnly(false);

//自动换行,设置为off关闭
editor.setOption("wrap", "free");

<!--var playbook_contents = '{{ playbook_text }}'.slice(6, -6);-->
var playbook_contents = '{{ playbook_text }}'.slice(6, -6).replace(/&quot;/g,'"').replace(/&#39;/g,"'");
<!--var playbook_contents = playbook_contents-->
editor.setValue(playbook_contents);


//启用提示菜单
ace.require("ace/ext/language_tools");
editor.setOptions({
        enableBasicAutocompletion: true,
        enableSnippets: true,
        enableLiveAutocompletion: true
    });

$('#submit_button').on('click', function () {
    var playbook_name = document.getElementById('name').value;
    var playbook_text = editor.getValue();
    if(playbook_name === '' || playbook_text === ''){
        swal('提示!', '请将表单填写完整～', 'warning');
        return false
    }
     $.ajax({
        type: "POST",
        url: "{% url 'task:edit' task.id %}",
        data:{'name': playbook_name, 'playbook_text': playbook_text},
        success: function(data){
            window.location.href = "{% url 'task:list' %}"
        }
    })
});


{% endblock %}

templates/tasks/task_add.html
{% extends "base.html" %}

{% block title %}任务申请{% endblock %}


{% block breadcrunb %}
  <h1>
     Dashboard
    <small>Version 2.0</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">任务申请</li>
  </ol>
{% endblock %}



{% block content %}


<!-- Main row -->
<div class="row">
<!-- Left col -->
<div class="col-md-12">

<!-- TABLE: LATEST ORDERS -->
<div class="box box-info">

<div class="box-header with-border">
  <h3 class="box-title">任务申请</h3>
  <div class="box-tools pull-right">
    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
    </button>
    <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
  </div>
</div>
<!-- /.box-header -->

<div class="box-body">
    <form method="post"  action="" class="form-horizontal" enctype="multipart/form-data" autocomplete="off">
        {% if errmsg %}
            <div class="alert alert-danger alert-dismissable">
                <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                {{ errmsg | safe }}
            </div>
        {% endif %}

        <div class="form-group"><label class="col-sm-2 control-label">任务名称：</label>
            <div class="col-sm-8">
                <input type="text" name ="name" id="task_name" class="form-control" value="" placeholder="任务名称" />
                {% for error in forms.name.errors %}<span style="color:red">{{ error }}</span>{% endfor %}
            </div>
        </div>
        <div class="hr-line-dashed"></div>
        <div class="form-group"><label class="col-sm-2 control-label">Playbook：</label>
            <div class="col-sm-8">
                 <input type="file" name="playbook" id="playbook" placeholder="Playbook">
                {% for error in forms.playbook.errors %}<span style="color:red">{{ error }}</span>{% endfor %}
            </div>
        </div>

        <div class="hr-line-dashed"></div>
        <div class="form-group">
             <div class="col-sm-4 col-sm-offset-2">
                <button type="button" class="btn btn-white">关闭</button>
                <button type="submit" class="btn btn-primary btn-add">添加任务</button>
            </div>
        </div>
 </form>
</div>

</div>
</div>
</div>




{% endblock %}

{% block js %}
{% endblock %}

templates/tasks/task_add1.html
{% extends 'base.html' %}


{% block title %}任务申请{% endblock %}


{% block breadcrunb %}
  <h1>
     Dashboard
    <small>Version 2.0</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">任务申请</li>
  </ol>
{% endblock %}



{% block content %}

<!-- Main row -->
<div class="row">
<!-- Left col -->
<div class="col-md-12">

<!-- TABLE: LATEST ORDERS -->
<div class="box box-info">

<div class="box-header with-border">
  <h3 class="box-title">任务申请</h3>
  <div class="box-tools pull-right">
    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
    </button>
    <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
  </div>
</div>
<!-- /.box-header -->

<div class="box-body">


    <form method="post" action="" class="form-horizontal">
        <div class="form-group"><label class="col-sm-2 control-label">任务名称：</label>
            <div class="col-sm-8">
                <input type="text" name ="name" id="name" class="form-control" placeholder="任务名称" />
                {% for error in forms.name.errors %}<span class="help-block m-b-none red">{{ error }}</span>{% endfor %}
            </div>
        </div>

        <div class="hr-line-dashed"></div>
        <div class="form-group"><label class="col-sm-2 control-label">脚本编辑：</label>
             <div class="col-sm-8">
                <pre id="code" class="ace_editor" style="min-height:400px"><textarea id="playbook_text" class="ace_text-input" name="playbook_text"></textarea></pre>
                 {% for error in forms.playbook_text.errors %}<span class="help-block m-b-none red">{{ error }}</span>{% endfor %}
             </div>
        </div>

        <div class="hr-line-dashed"></div>
        <div class="form-group">
            <div class="col-sm-4 col-sm-offset-2">
                <button id="submit_button" class="btn btn-primary" type="button">添加任务</button>
                <button class="btn btn-white" type="reset">重置</button>
            </div>
        </div>
    </form>
</div>
</div>
</div>
</div>

{% endblock %}


{% block js %}

//初始化对象
editor = ace.edit("code");

//设置风格和语言（更多风格和语言，请到github上相应目录查看）
theme = "clouds";
language = "yaml";
editor.setTheme("ace/theme/" + theme);
editor.session.setMode("ace/mode/" + language);

//字体大小
editor.setFontSize(18);

//设置只读（true时只读，用于展示代码）
editor.setReadOnly(false);

//自动换行,设置为off关闭
editor.setOption("wrap", "free");


//启用提示菜单
ace.require("ace/ext/language_tools");
editor.setOptions({
        enableBasicAutocompletion: true,
        enableSnippets: true,
        enableLiveAutocompletion: true
    });

$('#submit_button').on('click', function () {
    var playbook_name = document.getElementById('name').value;
    var playbook_text = editor.getValue();
    if(playbook_name === '' || playbook_text === ''){
        swal('提示!', '请将表单填写完整～', 'warning');
        return false
    }
     $.ajax({
        type: "POST",
        url: "{% url 'task:add1' %}",
        data:{'name': playbook_name, 'playbook_text': playbook_text},
        success: function(data){
            window.location.href = "{% url 'task:list' %}"
        }
    })
});

{% endblock %}

templates/tasks/task_detail.html
{% extends "base.html" %}

{% block title %}首页{% endblock %}


{% block breadcrunb %}
  <h1>
     Dashboard
    <small>Version 2.0</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">工单列表</li>
  </ol>
{% endblock %}



{% block content %}

<!-- Main row -->
<div class="row">
<!-- Left col -->
<div class="col-md-12">

<!-- TABLE: LATEST ORDERS -->
<div class="box box-info">
    <div class="box-header with-border">
      <h3 class="box-title">任务详情</h3>
      <div class="box-tools pull-right">
        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
        </button>
        <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
      </div>
    </div>
    <!-- /.box-header -->


<div class="box-body">

      <div>
          <pre style="color:#f8f8ff;background:#000000">{{ task.detail_result }}</pre>
      </div>
</div>
<!-- /.box-body -->

</div>
  <!-- /.box -->
</div>
<!-- /.col -->
</div>
<!-- /.row -->


{% endblock %}

{% block js %}
{% endblock %}

templates/tasks/tasks_list.html
{% extends "base.html" %}

{% block title %}首页{% endblock %}


{% block breadcrunb %}
  <h1>
     Dashboard
    <small>Version 2.0</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">任务列表</li>
  </ol>
{% endblock %}



{% block content %}

<!-- Main row -->
<div class="row">
<!-- Left col -->
<div class="col-md-12">

<!-- TABLE: LATEST ORDERS -->
<div class="box box-info">


    <div class="box-header with-border">
      <h3 class="box-title">任务列表</h3>
      <div class="box-tools pull-right">
        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
        </button>
        <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
      </div>
    </div>
    <!-- /.box-header -->

    <div class="box-body">

     <div style="margin-bottom: 10px;height: 30px" class="row">
        <form style="float: right;width: 20%;margin-right: 1%">
        <div  class="input-group">
            <input type="text" class="form-control" name="keyword"
                 placeholder="标题|内容|结果" value="{% if keyword %} {{ keyword }} {% endif %}">
            <div class="input-group-btn">
               <button id='search_btn' type="submit" class="btn btn-sm btn-primary">搜索</button>
            </div>
        </div>
        </form>
     </div>


    <div class="table-responsive">
    <table class="table table-bordered table-striped footable toggle-arrow-tiny" data-page-navigation=".paginations">
        <thead>
            <tr>
                <th class="text-center">任务名称</th>
                <th class="text-center">Playbook</th>
                <th class="text-center">执行状态</th>
                <th data-hide="all" class="text-center">执行结果</th>
                <th class="text-center">添加时间</th>
                <th class="text-center">操作</th>
            </tr>
        </thead>
        <tbody>
        {% for task in tasklist %}
            <tr class="gradeX">
                <td class="text-center">{{ task.name }}</td>
                <td class="text-center"> {{ task.playbook }} </td>
                <td id="status_{{ task.id }}" class="text-center"><span id="span" class="label {% ifequal task.status 'Y' %}label-success{% else %}label-danger{% endifequal %}">{{ task.get_status_display }}</span> </td>
                <td  id="exec_result_{{ task.id }}" class="text-center">
                    <table class="table">
                        <thead>
                        <tr  >
                        <th class="text-center info">主机</th>
                        <th class="text-center warning">不可达</th>
                        <th class="text-center active" >跳过</th>
                        <th class="text-center success">成功</th>
                        <th class="text-center success">改变</th>
                        <th class="text-center danger">失败</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for result in task.execresult_set.all %}
                            <tr>
                                <td class="info">{{ result.host }}</td>
                                <td class="warning">{{ result.unreachable }}</td>
                                <td class="active">{{ result.skipped }}</td>
                                <td class="success">{{ result.ok }}</td>
                                <td class="success">{{ result.changed }}</td>
                                <td class="danger">{{ result.failures }} </td>
                            </tr>
                                                {% endfor %}

                        </tbody>
                    </table>

                        <br />
                </td>
                <td class="text-center"> {{ task.exec_time}} </td>
                <td class="text-center">
                        <button type="button"  data-id="{{ task.id }}" id="{{ task.id }}" class="btn btn-xs btn-info btn-execute" {% if task.status == 'Y' %}disabled{% endif %}>执行</button>
                        <a href="{% url 'task:edit' task.id %}" class="btn btn-xs btn-primary" {% if task.status == 'Y' %}disabled{% endif %}>编辑</a>
                        <a href="{% url 'task:detail' task.id %}" class="btn btn-xs btn-success">详情</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    </div><!-- /.table-responsive -->

    <div class="row">
      <div class="col-sm-6">
         <div class="dataTables_info" id="editable_info" role="status" aria-live="polite">
             显示 [{{ paginator.count }}] 条数据中的 第 [{{ page_obj.start_index}}] 至 [{{ page_obj.end_index }}] 的数据
         </div>
      </div>

      {% include 'paginator.html' %}
    </div><!-- /.paginator -->

</div>
<!-- /.box-body -->

</div>
  <!-- /.box -->
</div>
<!-- /.col -->
</div>
<!-- /.row -->


{% endblock %}

{% block js %}

$('.btn-execute').click(function () {
    var task_id = $(this).attr('data-id');
    $.ajax({
        type: 'POST',
        url: "{% url 'task:list' %}",
        data: {'task_id': task_id},
        success: function (data) {
            console.log(data, typeof(data));
            if(data['task_status'] == 'Y'){
                console.log('Y，执行过了');
                $('#'+String(task_id)).attr("disabled", "disabled");
                var result_val = '';
                $.each(data['task_exec_result'], function (k,v) {
                    console.log(k, v);
                    result_val += k + '  不可达: '+ v['unreachable'] + '  跳过:' + v['skipped'] + '  成功:' + v['ok'] + '  改变:' + v['changed'] + '  失败:'+ v['failures'] +'\n';
                    console.log(result_val);
                });
                 document.getElementById('exec_result_'+ String(task_id)).innerText = result_val;

                 document.getElementById('span').innerText = '已执行';
                 document.getElementById('span').setAttribute('class', 'label label-success');
            }

        }
    })
})

$(document).ready(function() {
    $('.footable').footable();
});


{% endblock %}